name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-arm-none-eabi-toolchain
    - uses: jwlawson/actions-setup-cmake@v1.14
    - name: Configure
      run: |
        cmake -Bbuild .
    - name: Build
      run: |
        cmake --build build --config Debug --target all